from datetime import datetime

# print( datetime.now())
logs = open('logsTest.txt', 'a')
logs.write(str(datetime.now())+ '\n')
logs.write("ass" + '\n')
logs.write("ass" + '\n')
logs.write("ass" + '\n')
logs.write("ass" + '\n')
logs.write("ass" + '\n')
logs.write("ass" + '\n')
logs.write("ass" + '\n')
logs.write("ass" + '\n')
logs.write("ass" + '\n')
logs.write("ass" + '\n')
logs.write("ass" + '\n')
logs.close()